### ISSUE TITLE
current master branch is not working with globalize-4.0.0

### ISSUE THREAD

**Issue by rainchen** [refinery/refinerycms#2563]
I'm using 
`gem 'refinerycms', github: 'refinery/refinerycms', branch: 'master', ref: 'be9be68b27f8057aff690a518ab70942baa4cef5'`
in Gemfile

but when running `rails s`

there is an exception as

```
/Users/rain/.rvm/gems/ruby-1.9.3-p448/gems/globalize-4.0.0/lib/globalize/active_record/act_macro.rb:9:in `map': undefined method `to_sym' for {:include=>:seo_meta}:Hash (NoMethodError)
    from /Users/rain/.rvm/gems/ruby-1.9.3-p448/gems/globalize-4.0.0/lib/globalize/active_record/act_macro.rb:9:in `translates'
    from /Users/rain/.rvm/gems/ruby-1.9.3-p448/bundler/gems/refinerycms-be9be68b27f8/pages/app/models/refinery/page.rb:10:in `<class:Page>'
    from /Users/rain/.rvm/gems/ruby-1.9.3-p448/bundler/gems/refinerycms-be9be68b27f8/pages/app/models/refinery/page.rb:7:in `<module:Refinery>'
    from /Users/rain/.rvm/gems/ruby-1.9.3-p448/bundler/gems/refinerycms-be9be68b27f8/pages/app/models/refinery/page.rb:6:in `<top (required)>'

```

```
# /Users/rain/.rvm/gems/ruby-1.9.3-p448/gems/globalize-4.0.0/lib/globalize/active_record/act_macro.rb:9
  module Globalize
  module ActiveRecord
    module ActMacro
      def translates(*attr_names)
        # Bypass setup_translates! if the initial bootstrapping is done already.
        setup_translates!(attr_names.extract_options!) unless translates?

        # Add any extra translatable attributes.
        attr_names = attr_names.map(&:to_sym)



```

```
# /Users/rain/.rvm/gems/ruby-1.9.3-p448/bundler/gems/refinerycms-be9be68b27f8/pages/app/models/refinery/page.rb
module Refinery
  class Page < Core::BaseModel
    extend FriendlyId

    translates :title, :menu_title, :custom_slug, :slug, :include => :seo_meta

```

Am I alone with this?
