### ISSUE TITLE
NoMethodError in Refinery::Admin::ImagesController#create

### ISSUE THREAD

**Issue by cemali** [refinery/refinerycms#2099]
I am working with refinerycms with rails 3.2 and I was attempting to upload a photo and received this error message. Can anyone give any assistance on this error from the cms? 

best regards,

Cemali.

```
: NoMethodError in Refinery::Admin::ImagesController#create

undefined method `exitstatus' for nil:NilClass

Rails.root: C:/Sites2/all4uplumbing
Application Trace | Framework Trace | Full Trace

Request

Parameters:

{"utf8"=>"✓",
 "authenticity_token"=>"C1F4hlkK4OPtEMK4VZbw7OV05E1fHyc0PXxHYr1Atpg=",
 "image"=>{"image"=>[#<ActionDispatch::Http::UploadedFile:0x81c0eb8 @original_filename="breGrad300.png",
 @content_type="image/png",
 @headers="Content-Disposition: form-data; name=\"image[image][]\"; filename=\"breGrad300.png\"\r\nContent-Type: image/png\r\n",
 @tempfile=#<File:C:/Users/WOODST~1/AppData/Local/Temp/RackMultipart20121226-5008-dkba59 (closed)>>]},
 "wymeditor"=>"true",
 "modal"=>"true",
 "dialog"=>"true",
 "insert"=>"true",
 "locale"=>:en}

Show session dump

Show env dump
Response

Headers:

None
```
