### ISSUE TITLE
 undefined method `admin_dialogs_path' for #<Module:... on Heroku

### ISSUE THREAD

**Issue by julesce** [refinery/refinerycms#1751]
Hi guys,

I'm getting the following error when deploying any 2.0.4 or 2.0.5 refinerycms apps to Heroku:

```
-----> Preparing app for Rails asset pipeline
   Running: rake assets:precompile
   rake aborted!
   undefined method `admin_dialogs_path' for #<Module:0x00000006d06708>
   (in /tmp/build_13ex2hfe5y1g5/vendor/bundle/ruby/1.9.1/gems/refinerycms-core-2.0.5/app/assets/javascripts/refinery/boot_wym.js.erb)
```

So for now I'm just sticking with 2.0.3... is there a setting that needs to be changed from the way it works in 2.0.3?

Thanks!

James
